### PR TITLE
Fix a possible race with concurrent encryption with the same config

### LINKED ISSUE #92: Concurrent calls of EncryptLayer seem to be racy
c/image can copy layers in parallel; that involves concurrent calls of `EncryptLayer` with the same `EncryptConfig`.

Looking at https://github.com/containers/ocicrypt/blob/ffc163c18e970386fcd1b35acf2d350c8665d080/keywrap/pkcs11/keywrapper_pkcs11.go#L44 , it seems that that could concurrently write to the same array underlying the `ec.Parameters["pkcs11-pubkeys"]` array.

That seems to be possible in principle in Go, as demonstrated by
```go
package main

import "fmt"

func main() {
	a := []int{1, 11, 12, 13}
	a = append(a, 14, 15) // Creates a backing array with extra capacity
	b := append(a, 2, 21) // Writes to the backing array of a
	c := append(a, 3, 31) // ALSO writes to the backing array of a

	fmt.Printf("%#v@%d %#v@%d %#v@%d\n", a, cap(a), b, cap(b), c, cap(c))

	a[0] = 10
	fmt.Printf("%#v@%d %#v@%d %#v@%d\n", a, cap(a), b, cap(b), c, cap(c)) // See that both b and c are updated - and b contains c’s data
}
```

### PR DESCRIPTION
**Pull request by mtrmac**
`append()` can allocate arrays with `cap(s) > len(s)`, and future `append()` calls would then just write to the free slots; doing that from multiple goroutines would race.

Fixes #92, which contains a demonstration.

(I didn’t test this in practice.)

### CODE REVIEW

File: keywrap/pkcs11/keywrapper_pkcs11.go [hunk 1]
```diff
@@ -41,7 +41,11 @@ func NewKeyWrapper() keywrap.KeyWrapper {
 // WrapKeys wraps the session key for recpients and encrypts the optsData, which
 // describe the symmetric key used for encrypting the layer
 func (kw *pkcs11KeyWrapper) WrapKeys(ec *config.EncryptConfig, optsData []byte) ([]byte, error) {
-	pkcs11Recipients, err := addPubKeys(&ec.DecryptConfig, append(ec.Parameters["pkcs11-pubkeys"], ec.Parameters["pkcs11-yamls"]...))
+	// append({}, ...) allocates a fresh backing array, and that's necessary to guarantee concurrent calls to WrapKeys (as in c/image/copy.Image)
+	// can't race writing to the same backing array.
+	pubKeys := append([][]byte{}, ec.Parameters["pkcs11-pubkeys"]...) // In Go 1.21, slices.Clone(ec.Parameters["pkcs11-pubkeys"])
+	pubKeys = append(pubKeys, ec.Parameters["pkcs11-yamls"]...)
```
Comment (stefanberger) [inline keywrap/pkcs11/keywrapper_pkcs11.go:47]: Regarding the patch description: This would sound like local variables were raceable by other co-routines. Can this be?

Comment (mtrmac) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: `ec` is not a local variable; it is provided to `copy.Image`, which spins up (typically) 6 goroutines concurrently copying image layers. Therefore `ec.Parameters` is possibly concurrently read by those goroutines, and in the current version of the code, `append(ec.Parameters[…]` is possibly concurrently called on the same slice.

From a quick search, `append` amounts to probaly something like https://github.com/golang/go/blob/2968f5623c71d0e8e7be6e117939c5f585bb0620/src/cmd/compile/internal/walk/builtin.go#L43 , calling https://github.com/golang/go/blob/2968f5623c71d0e8e7be6e117939c5f585bb0620/src/runtime/slice.go#L174 , which (to avoid an O(N^2) behavior on repeated appends), can create a slice with `cap(slice) > len(slice)`. And with such a slice, `append(slice_with_large_cap, new_elem)` is basically `slice_with_large_cap[len++] = new_elem` — a concurrent write to memory shared across goroutines.

---

The fix forces creation of a new slice, local to this function.

Comment (stefanberger) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: How is the slice shared across go-routines? It's `ec` that in your case is shared across go-routines, but the slice should be local to each go-routine, no?

Comment (mtrmac) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: `ec` is shared, and potentially concurrently read from multiple goroutines
→ they all share, and potentially concurrently read, the `ec.Parameters` map
→ they all share, and potentially concurrently read, the `ec.Parameters["pkcs11-pubkeys"]` slice value
→ they all share the _array_ underlying that slice
→ they all potentially write to that backing array.

Comment (stefanberger) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: In your proposed solution you are now creating an explicit slice `pubKeys` that presumably was done implicitly also before in `append(ec.Parameters["pkcs11-pubkeys"], ec.Parameters["pkcs11-yamls"]...)`.

Per what you are saying above the `ec` is shared and 'they all potentially write to that backing array'. They all write to the backing array of their own private slice 'pubKeys', right?

Comment (stefanberger) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: @lumjjb Comments?

Comment (stefanberger) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: I could see a race if they were writing to a shared `pubKeys` slice but I don't see that happening. Nor do I see races due to reading from `ec`.

Comment (mtrmac) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: > In your proposed solution you are now creating an explicit slice `pubKeys` that presumably was done implicitly also before in `append(ec.Parameters["pkcs11-pubkeys"], ec.Parameters["pkcs11-yamls"]...)`.

No. `append` modifies the backing array of the first parameter. It does not _always_ create a new array.

Comment (stefanberger) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: > > In your proposed solution you are now creating an explicit slice `pubKeys` that presumably was done implicitly also before in `append(ec.Parameters["pkcs11-pubkeys"], ec.Parameters["pkcs11-yamls"]...)`.
> 
> No. `append` modifies the backing array of the first parameter. It does not _always_ create a new array.

But each coroutine has its own slice. So how would one coroutine influence another one?

Comment (mtrmac) [reply keywrap/pkcs11/keywrapper_pkcs11.go:47]: Its own slice, not its own backing array. Each slice is individually grown, but they all overwrite the previously-free slots in the array.

**Review by stefanberger — APPROVED** [review]

**Comment by mtrmac** [comment]
A full self-contained demonstration:
```go
package main

import (
	"fmt"
	"sync"
	"time"
)

func goroutine(wg *sync.WaitGroup, sharedSlice []int, i int) {
	defer wg.Done()

	privateSlice := append(sharedSlice, i)
	oldValue := privateSlice[len(privateSlice)-1]
	// This is already slow enough that the "full" value is frequently overwritten by another goroutine
	fmt.Printf("goroutine %d: immediate %d; full %#v@%v\n", i, oldValue, privateSlice, cap(privateSlice))

	time.Sleep(100 * time.Millisecond) // Give ample time for other goroutines to run

	newValue := privateSlice[len(privateSlice)-1]
	if newValue != i {
		panic(fmt.Sprintf("goroutine %d: immediate %d, after sleep %d; full %#v@%v", i, oldValue, newValue, privateSlice, cap(privateSlice)))
	}
}

func main() {
	sharedSlice := []int{0, 0, 0, 0}
	// Creates a backing array with extra capacity. (Alternatively, this could use the 3-argument version of make(),
	// but this demonstrates that this happens completely naturally just using append().)
	sharedSlice = append(sharedSlice, 0, 0)
	fmt.Printf("shared: %#v@%d\n", sharedSlice, cap(sharedSlice))

	wg := sync.WaitGroup{}
	for i := 0; i < 10; i++ {
		wg.Add(1)
		go goroutine(&wg, sharedSlice, i)
	}
	wg.Wait()
}
```

One output:
```
shared: []int{0, 0, 0, 0, 0, 0}@8
goroutine 9: immediate 9; full []int{0, 0, 0, 0, 0, 0, 4}@8
goroutine 7: immediate 7; full []int{0, 0, 0, 0, 0, 0, 7}@8
goroutine 8: immediate 8; full []int{0, 0, 0, 0, 0, 0, 8}@8
goroutine 4: immediate 4; full []int{0, 0, 0, 0, 0, 0, 2}@8
goroutine 2: immediate 2; full []int{0, 0, 0, 0, 0, 0, 2}@8
goroutine 5: immediate 5; full []int{0, 0, 0, 0, 0, 0, 5}@8
goroutine 3: immediate 3; full []int{0, 0, 0, 0, 0, 0, 3}@8
goroutine 0: immediate 0; full []int{0, 0, 0, 0, 0, 0, 0}@8
goroutine 6: immediate 6; full []int{0, 0, 0, 0, 0, 0, 0}@8
goroutine 1: immediate 1; full []int{0, 0, 0, 0, 0, 0, 1}@8
panic: goroutine 4: immediate 4, after sleep 1; full []int{0, 0, 0, 0, 0, 0, 1}@8
…
```

**Comment by stefanberger** [comment]
Thanks. Would have never found it.
